{
  "source": "enGB",
  "key": "da9fccae-1b36-4185-bff5-a80fc22c415c",
  "ownerGuid": "542a4209490337740a2c88a7cbc7b96a",
  "languages": [
    {
      "locale": "enGB",
      "text": "Some internal exception caused the socket code to fail. This may happen if you attempt to connect locally, but the server is not available.",
      "modification_date": "2023-09-19T16:59:01.6749921+00:00",
      "translated_from": "ruRU",
      "translation_date": "2023-09-19T16:59:01.6749924+00:00",
      "original_text": "Внутреннее исключение привело к сбою кода сокета. Это может произойти, если вы пытаетесь подключиться локально, но сервер недоступен.",
      "traits": [
        {
          "trait": "Edited",
          "trait_date": "2023-09-19T16:59:01.6749943+00:00",
          "locale_text": "Some internal exception caused the socket code to fail. This may happen if you attempt to connect locally, but the server is not available."
        },
        {
          "trait": "JL_ed",
          "trait_date": "2023-09-19T16:59:01.6749946+00:00",
          "locale_text": "Some internal exception caused the socket code to fail. This may happen if you attempt to connect locally, but the server is not available."
        }
      ]
    },
    {
      "locale": "ruRU",
      "text": "Внутреннее исключение привело к сбою кода сокета. Это может произойти, если вы пытаетесь подключиться локально, но сервер недоступен.",
      "modification_date": "2023-06-28T12:22:17.3587001+03:00"
    },
    {
      "locale": "deDE",
      "text": "Eine interne Ausnahme hat den Socket-Code zum Scheitern gebracht. Dies kann passieren, wenn du versuchst, eine lokale Verbindung herzustellen, aber der Server nicht verfügbar ist.",
      "modification_date": "2023-10-18T15:38:01.5323943+00:00",
      "translated_from": "enGB",
      "translation_date": "2023-10-18T19:10:51.2039334+00:00",
      "original_text": "Some internal exception caused the socket code to fail. This may happen if you attempt to connect locally, but the server is not available.",
      "traits": [
        {
          "trait": "Translated",
          "trait_date": "2023-10-18T19:10:51.2039346+00:00",
          "locale_text": "Eine interne Ausnahme hat den Socket-Code zum Scheitern gebracht. Dies kann passieren, wenn du versuchst, eine lokale Verbindung herzustellen, aber der Server nicht verfügbar ist."
        }
      ]
    },
    {
      "locale": "frFR",
      "text": "Une exception interne a provoqué l'échec du code des sockets. Celle-ci peut être due à une tentative de connexion locale alors que le serveur n'est pas disponible.",
      "modification_date": "2023-10-18T15:56:11.5792853+00:00",
      "translated_from": "enGB",
      "translation_date": "2023-10-18T19:19:45.6518176+00:00",
      "original_text": "Some internal exception caused the socket code to fail. This may happen if you attempt to connect locally, but the server is not available.",
      "traits": [
        {
          "trait": "Translated",
          "trait_date": "2023-10-18T19:19:45.6518192+00:00",
          "locale_text": "Une exception interne a provoqué l'échec du code des sockets. Celle-ci peut être due à une tentative de connexion locale alors que le serveur n'est pas disponible."
        }
      ]
    },
    {
      "locale": "zhCN",
      "text": "发生内部异常，套接代码失败。当您进行本地连接，但服务器无法访问时，可能会发生这种情况。",
      "modification_date": "2023-09-29T08:19:48.0300571+00:00",
      "translated_from": "enGB",
      "translation_date": "2023-09-29T08:19:48.0300573+00:00",
      "original_text": "Some internal exception caused the socket code to fail. This may happen if you attempt to connect locally, but the server is not available.",
      "traits": [
        {
          "trait": "Translated",
          "trait_date": "2023-09-29T08:19:48.0300579+00:00",
          "locale_text": "发生内部异常，套接代码失败。当您进行本地连接，但服务器无法访问时，可能会发生这种情况。"
        }
      ]
    },
    {
      "locale": "esES",
      "text": "Una excepción interna ha hecho que el código de socket falle. Esto puede suceder al intentar conectarte de forma local si el servidor no está disponible.",
      "modification_date": "2023-09-29T08:19:47.4644099+00:00",
      "translated_from": "enGB",
      "translation_date": "2023-09-29T08:19:47.4644107+00:00",
      "original_text": "Some internal exception caused the socket code to fail. This may happen if you attempt to connect locally, but the server is not available.",
      "traits": [
        {
          "trait": "Translated",
          "trait_date": "2023-09-29T08:19:47.4644123+00:00",
          "locale_text": "Una excepción interna ha hecho que el código de socket falle. Esto puede suceder al intentar conectarte de forma local si el servidor no está disponible."
        }
      ]
    },
    {
      "locale": "jaJP",
      "text": "何らかの内部異常によりソケット・コードが機能しませんでした。この現象は、ローカル接続の試行時にサーバーが利用できない場合に起きることがあります。",
      "modification_date": "2023-11-14T10:38:20.7658703+00:00",
      "translated_from": "enGB",
      "translation_date": "2023-11-14T10:38:20.7658707+00:00",
      "original_text": "Some internal exception caused the socket code to fail. This may happen if you attempt to connect locally, but the server is not available.",
      "traits": [
        {
          "trait": "Translated",
          "trait_date": "2023-11-14T10:38:20.7658729+00:00",
          "locale_text": "何らかの内部異常によりソケット・コードが機能しませんでした。この現象は、ローカル接続の試行時にサーバーが利用できない場合に起きることがあります。"
        }
      ]
    }
  ],
  "string_traits": [
    {
      "trait": "OtherLocs_ToReview",
      "trait_date": "2023-09-26T16:57:56.4108006+00:00",
      "locale_text": ""
    }
  ]
}